[package]
name = "lz"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.0"
colored = "2.0.0"
is_executable = "1.0.1"
